### ISSUE TITLE
Tutorial not compatible with Eliom dev on master

### ISSUE THREAD

**Issue by dannywillems** [ocsigen/tutorial#39]
Most of tutorials are not compatible with the actual version of Eliom. Services are not created in the way for example, and nothing is documented about creating external services or services with GET and POST.

We lost a lot of time to know how to do something because (for example) we need to go in some code (like EBA) to have an idea of POST services (no explanation about Eliom_param.unit as first parameter for Eliom_service.Post, could I have an explanation?)

A deep low level explanation about services could be interesting.

**Comment by vasilisp** [comment]
I have updated the tutorial en masse, so there may still be incompatibilities. We need to do a thorough pass through the tutorial and manuals before the upcoming releases.

**Comment by dannywillems** [comment]
@vasilisp Do you think I must reopen?
