### ISSUE TITLE
Syntax error wiki syntax

### ISSUE THREAD

**Issue by dannywillems** [ocsigen/tutorial#44]
List of syntax error.
- [ ] http://ocsigen.org/tuto/dev/manual/application: bottom --> "Syntax error wiki syntax". 
- [ ] http://ocsigen.org/eliom/dev/manual/server-links: "Forms towards GET services" section --> The modules Error a_api: invalid ocaml id "Eliom_content.Html5.D.Form" and Error a_api: invalid ocaml id "Eliom_content.Html5.F.Form" (same in 5.0 version).

Meaning:
- [ ] --> not fixed.
- [x] --> fixed.

**Comment by Drup** [comment]
Look like it's fixed.
