### ISSUE TITLE
Tutorial for eliom-5.0 mentions Eliom_base_app, which is hardly compatible

### ISSUE THREAD

**Issue by FlorentBecker** [ocsigen/tutorial#45]
The tutorial on ocsigen.org mentions Eliom_base_app as a starting point for complex sites with ocsigen, but:
- it has been renamed ocsigen-start
- it is meant to be used with eliom-dev

It would probably be best to tag some eliom-5 compatible revisions of ocsigen-start and its dependencies and point to these tags.

**Comment by dannywillems** [comment]
@FlorentBecker It's in progess.

**Comment by Drup** [comment]
Done.
