### ISSUE TITLE
eliom-destillery CLI example is outdated

### ISSUE THREAD

**Issue by avanov** [ocsigen/tutorial#8]
http://ocsigen.org/tutorial/basicwebsite
The following example is outdated

> eliom-distillery -name mysite -template basic -target-directory mysite

Here's what I get when trying to follow the tutorial (eliom 3.0.3):

``` bash
$ eliom-destillery -name mysite -template basic -target-directory mysite
/home/vagrant/.opam/4.01.0/bin/eliom-destillery: unknown option `-target-directory'.
```

It works, however, with the following arguments:

``` bash
$ eliom-destillery -name mysite -template basic -destination mysite
```

So `-target-directory` should be replaced by `-destination`.

**Comment by dannywillems** [comment]
The page doesn't exist anymore and all eliom-distillery examples are up-to-date. I close.
